SET (CMAKE_CXX_FLAGS "-xCORE_AVX512" CACHE STRING "")

SET(NETCDF_DIR $ENV{NETCDF_ROOT} CACHE FILEPATH "")
SET(NETCDF_Fortran_DIR $ENV{NETCDFF_ROOT} CACHE FILEPATH "")
SET(PNETCDF_DIR $ENV{PNETCDF_ROOT} CACHE FILEPATH "")
SET(ZLIB_DIR $ENV{ZLIB_ROOT} CACHE FILEPATH "")

SET(NETCDFF_DIR $ENV{TESTBED_ROOT}/netcdf-fortran CACHE FILEPATH "")
SET(NetcdfF_LIBRARY -L$ENV{TESTBED_ROOT}/netcdf-fortran/lib64 -lnetcdff -lhdf5_hl -lhdf5 CACHE LIST "")

SET(NETCDF_Fortran_DIR $ENV{TESTBED_ROOT}/netcdf-fortran CACHE FILEPATH "")
SET(NETCDF_Fortran_INCLUDE_DIR $ENV{TESTBED_ROOT}/netcdf-fortran/include CACHE PATH "")
# Hack to avoid pio cmake issue
SET(NETCDF_Fortran_FOUND TRUE CACHE BOOL "")

SET(HOMME_FIND_BLASLAPACK TRUE CACHE BOOL "")

SET(USE_QUEUING FALSE CACHE BOOL "")

SET(CMAKE_C_COMPILER "mpicc" CACHE STRING "")
SET(CMAKE_CXX_COMPILER "mpicxx" CACHE STRING "")
SET(CMAKE_Fortran_COMPILER "mpifort" CACHE STRING "")

SET(ENABLE_CUDA FALSE CACHE BOOL "")

SET(PIO_USE_MPIMOD OFF CACHE BOOL "")

SET(USE_TRILINOS OFF CACHE BOOL "")
