#!/bin/bash -f
#SBATCH --job-name baro
#SBATCH -p ec
#SBATCH --time=00:120:00
#SBATCH --nodes=8
#SBATCH --output=sout%j
#SBATCH --error=serr%j
#SBATCH --account=FY150001

source ~/tinman-modules.sh

dirXX=/ascldap/users/onguba/runhomme/bldxx/

#run jw test with rsplit=3
mpiexec -n 128 ${dirXX}/test_execs/prtcB_flat_c/prtcB_flat_c < input-baro-rsplit3-c72.nl > baro-r3-c72-out
mpiexec -n 128 ${dirXX}/test_execs/prtcB_flat/prtcB_flat < input-baro-rsplit3-f72.nl > baro-r3-f72-out
#run with rsplit=0
mpiexec -n 128 ${dirXX}/test_execs/prtcB_flat_c/prtcB_flat_c < input-baro-rsplit0-c72.nl > baro-r0-c72-out
mpiexec -n 128 ${dirXX}/test_execs/prtcB_flat/prtcB_flat < input-baro-rsplit0-f72.nl > baro-r0-f72-out

#compare xx C and F executables
mpiexec -n 1 ${dirXX}/utils/cprnc/cprnc movies/cxx72-r3-jw_baroclinic1.nc movies/f72-r3-jw_baroclinic1.nc &> compare72-baro-c-f-r3-file1
mpiexec -n 1 ${dirXX}/utils/cprnc/cprnc movies/cxx72-r3-jw_baroclinic2.nc movies/f72-r3-jw_baroclinic2.nc &> compare72-baro-c-f-r3-file2

mpiexec -n 1 ${dirXX}/utils/cprnc/cprnc movies/cxx72-r0-jw_baroclinic1.nc movies/f72-r0-jw_baroclinic1.nc &> compare72-baro-c-f-r0-file1
mpiexec -n 1 ${dirXX}/utils/cprnc/cprnc movies/cxx72-r0-jw_baroclinic2.nc movies/f72-r0-jw_baroclinic2.nc &> compare72-baro-c-f-r0-file2




