# CMake initial cache file for Sandia's bowman
# tested with stock intel & openmpi

SET (CMAKE_BUILD_TYPE "" CACHE STRING "")
SET (CMAKE_Fortran_COMPILER mpif90 CACHE FILEPATH "")
SET (CMAKE_C_COMPILER mpicc CACHE FILEPATH "")
SET (CMAKE_CXX_COMPILER mpicxx CACHE FILEPATH "")

SET (CMAKE_Fortran_FLAGS "-xMIC_AVX512 -O1 -g" CACHE STRING "")
SET (CMAKE_C_FLAGS "-xMIC_AVX512 -O3 -g" CACHE STRING "")
SET (CMAKE_CXX_FLAGS "-xMIC_AVX512 -O3 -g" CACHE STRING "")

SET (NETCDF_DIR $ENV{NETCDF_ROOT} CACHE FILEPATH "")
SET (NETCDFF_DIR $ENV{TESTBED_ROOT}/netcdf-fortran CACHE FILEPATH "")
SET (NetcdfF_LIBRARY -L$ENV{TESTBED_ROOT}/netcdf-fortran/lib64 -lnetcdff -lhdf5_hl -lhdf5 CACHE FILEPATH "")
SET (NETCDF_Fortran_DIR $ENV{TESTBED_ROOT}/netcdf-fortran CACHE FILEPATH "")
SET (NETCDF_Fortran_INCLUDE_DIR $ENV{TESTBED_ROOT}/netcdf-fortran/include CACHE FILEPATH "")

SET (PNETCDF_DIR $ENV{PNETCDF_ROOT} CACHE FILEPATH "")
SET (ZLIB_DIR $ENV{ZLIB_ROOT} CACHE FILEPATH "")
SET (KOKKOS_PATH $ENV{TESTBED_ROOT}/kokkos-release CACHE FILEPATH "")

SET (USE_QUEUING FALSE CACHE BOOL "")
SET (HOMME_FIND_BLASLAPACK TRUE CACHE BOOL "")

SET (ENABLE_INTEL_PHI TRUE CACHE BOOL "")

SET (USE_TRILINOS OFF CACHE BOOL "")
SET (KOKKOS_PATH $ENV{TESTBED_ROOT}/kokkos-release CACHE STRING "")

SET(USE_MPI_OPTIONS "--bind-to core" CACHE STRING "")
