
SET(NETCDF_DIR $ENV{NETCDF_ROOT} CACHE FILEPATH "")
SET(PNETCDF_DIR $ENV{PNETCDF_ROOT} CACHE FILEPATH "")

SET(NETCDF_PREFIX /home/mdeakin/prefix)
SET(NetcdfF_LIBRARY ${NETCDF_PREFIX}/lib64/libnetcdff.so -lhdf5_hl -lhdf5 -ldl CACHE LIST "")
SET(NetcdfF_INCLUDE_DIR ${NETCDF_PREFIX}/include CACHE FILEPATH "")

SET(HOMME_FIND_BLASLAPACK TRUE CACHE BOOL "")

SET(USE_QUEUING FALSE CACHE BOOL "")

