
SET(NETCDF_DIR $ENV{NETCDF_ROOT} CACHE FILEPATH "")
SET(PNETCDF_DIR $ENV{PNETCDF_ROOT} CACHE FILEPATH "")

SET(MDEAKIN_PREFIX /home/mdeakin/prefix)
SET(NetcdfF_LIBRARY ${MDEAKIN_PREFIX}/lib64/libnetcdff.so CACHE FILEPATH "")

SET(HOMME_FIND_BLASLAPACK TRUE CACHE BOOL "")

SET(USE_QUEUING FALSE CACHE BOOL "")

