
# Set up Trilinos as an external project
SET(TRILINOS_REPO "https://github.com/trilinos/Trilinos")
SET(TRILINOS_SRCDIR "${CMAKE_SOURCE_DIR}/../../cime/externals")

SET(EXECUTION_SPACES "-DTPL_ENABLE_MPI=ON")

FIND_PACKAGE(CUDA QUIET)
IF(${CUDA_FOUND})
  OPTION(ENABLE_CUDA "Whether or not to enable CUDA" ON)
  IF(${ENABLE_CUDA})
    SET(EXECUTION_SPACES "${EXECUTION_SPACES} -DTPL_ENABLE_CUDA=ON")
  ENDIF()
ENDIF()

SET(TRILINOS_INSTALL_DIR "~/prefix" CACHE FILEPATH "Where to install Trilinos")

SET(TRILINOS_CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${TRILINOS_INSTALL_DIR} -DTrilinos_ENABLE_Kokkos=ON ${EXECUTION_SPACES}")

externalproject_add(Trilinos

  GIT_REPOSITORY ${TRILINOS_REPO}
  GIT_TAG master
  UPDATE_COMMAND ""
  PATCH_COMMAND ""

  SOURCE_DIR ${TRILINOS_SRCDIR}

  CMAKE_ARGS ${TRILINOS_CMAKE_ARGS}
)
